config/routes.rb
Ananta::Application.routes.draw do

	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config

	post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
	
	resources :sessions, :only => [:index]

	resources :comments, :only => [:index, :show, :create, :edit, :update, :destroy]
	resources :locations, :only => [:create, :update]

	resources :questions, :only => [:index, :show, :create, :update] do
		collection do
			get 'page/:page', :action => :index
			get 'random_unanswered'
		end
		resources :answers, :only => [:index, :show, :create, :update] do
			resources :comments, :only => [:create]
		end
	end

	resources :project_memberships, :only => [] do
		member do
			post 'accept'
			post 'reject'
		end
	end

	resources :projects, :only => [:index, :show] do
		collection do
			get 'page/:page', :action => :index
			get 'random'
		end
		resources :comments, :only => [:index]
	end

	resources :images, :only => [:create, :update, :destroy]

	match '/render_nav' => 'users#render_nav' # ujs render user_nav. generally called after ajax login
	resources :users, :only => [:index] do
		collection do
			get 'random'
		end
	end
	devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations', :sessions => 'users/sessions' }
	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
		get '/register' => 'devise/registrations#new'
	end

	match '/me' => 'pages#me' 
	match '/tb' => 'pages#tb' if Rails.env == 'development'
	match '/about' => 'pages#about'
	match '/robots.txt' => 'pages#robots'

	root :to => 'pages#home'

	resources :profiles, :path => '' do
		member do
			get :edit_location
		end
	end
	resources :users, :path => '', :only => [] do
		resources :projects, :path => '', :except => [:index] do
			member do
				post "join"
				post "leave"
			end
		end
	end

	# See how all your routes lay out with "rake routes"
end

app/models/question.rb
# A question must be binary (yes, no)
# It can be answered with Yes, No, Don't Care. 
# The questions with more Yes, No answers and fewer Don't Cares get displayed more.

# require File.join(Rails.root, 'lib/ananta/vote')

class Question < ActiveRecord::Base

	#########################
	# Callbacks & Misc method calls (e.g. devise for, acts_as_whatever )
	#########################
	include Ananta::Vote

	before_save :update_answer_count, :if => :answer_counts_changed?

	# Vote
	acts_as_voteable 

	# Versioning
	has_paper_trail

	# TODOooooooooo: add relevance. to be queried in a 0-1000 range slider after every answer is submited. saved as question_relevance on answer and averaged in a worker and stored on quesiton as avg_relevance. bias the ui to users with really nice track pads ;) and increase relevence by the durration and vigor with which a user rubs an answered question, make the question heat up (dark to red) as the user rubs. AND HAVE SPARKS COME OUT WHEN A QUESTION GETS RED HOT! Do not count the relevance of the user who created the question towards the average

	# Question state machine
	state_machine :initial => :published do
		event :unpublish do
			transition :published => :unpublished
		end

		event :publish do
			transition :unpublished => :published
		end

		# Only moderaters should be allowed to kill a question
		# Check ability model
		event :kill do
			transition [:published, :unpublished] => :killed
		end
	end

	#########################
	# Setup attributes (reader, accessible, protected)
	#########################
	#attr_reader
	#attr_accessor
	attr_accessible :question, :questionable_url, :questionable_sid, :questionable_controller, :questionable_action, :on => :create
	attr_accessible :cast_vote, :state_event


	#########################
	# Associations
	#########################
	belongs_to :user 
	has_many :answers, :dependent => :destroy
	has_many :comments, :through => :answers, :source => :comment, :dependent => :destroy
	has_many :views, :as => :viewable, :dependent => :destroy


	#########################
	# Validations
	#########################
	validates :user_id, :presence => true
	# validates :questionable_url, :presence => true
	validates :question, :length => { :in => 15..141 }, :uniqueness => {:scope => [:questionable_url], :message => 'has already been asked on this page'}, :format => { :with => /\?$/, :message => "must end with a question mark (?)" }
	

	#########################
	# Scopes
	#########################
	scope :published, where(:state => 'published')
	scope :answered, where("answer_count > ?", 0)
	scope :answered_by, lambda { |user_id| joins(:answers).where("answers.user_id = ?", user_id)}
	scope :unanswered, where("answer_count = ?", 0)
	scope :unanswered_by, lambda { |user_id| where( "answer_count = ? OR id NOT IN (?)", 0, ( [0] | ( User.find(user_id).answers.pluck(:question_id) rescue [] ) ) ) }
	scope :q_url, lambda { |q_url| where("questionable_url LIKE ?", "%#{q_url}%") } 
	scope :q_sid, lambda { |q_sid| where("questionable_sid = ?", q_sid) } 
	scope :q_controller, lambda { |q_con| where("questionable_controller = ?", q_con) } 
	scope :q_action, lambda { |q_act| where("questionable_action = ?", q_act) } 

	#########################
	# Public Class Methods ( def self.method_name )
	#########################

	## One line description
	## maybe two
	#def self.my_method
	#
	#end


	#########################
	# Public Instance Methods ( def method_name )
	#########################

	# Similar to the scope, but for the current record
	def answered_by user_id
		answers.where("user_id = ?", user_id).first
	end

	# Returns a new unsaved answerd
	def answer params, answering_user
		attrs = {}
		attrs[:state_event] = params[:state_event]
		attrs[:user_id] = answering_user.try(:id)
		unless (params[:comment].blank? rescue true)
			attrs[:comment_attributes] = {}
			attrs[:comment_attributes][:comment] = params[:comment]
			attrs[:comment_attributes][:user_id] = attrs[:user_id]	
		end

		self.answers.new attrs
	end
	

	#########################
	# Protected Methods
	#########################
protected

	# Return true if any of the answer counts change
	def answer_counts_changed?
		(yes_count_changed? or no_count_changed? or dont_care_count_changed?) ? true : false
	end

	# Increment or decrement answer_count
	def update_answer_count
		c = 0
		c = c + changes[:yes_count][1] - changes[:yes_count][0] if yes_count_changed?
		c = c + changes[:no_count][1] - changes[:no_count][0] if no_count_changed?
		c = c + changes[:dont_care_count][1] - changes[:dont_care_count][0] if dont_care_count_changed?
		self.answer_count = self.answer_count + c
	end


	#########################
	# Private Methods
	#########################
private

	# Same as Public Instance Methods


end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
	#########################
	# Config via inherited_resources https://github.com/josevalim/inherited_resources 
	#########################
	respond_to :js, :html, :json
	actions :index, :show, :create, :update


	#########################
	# Scopes via has_scope https://github.com/plataformatec/has_scope
	#########################
	has_scope :published, :type => :boolean, :only => :index, :default => true
	has_scope :answered, :type => :boolean, :only => :index
	has_scope :answered_by, :only => :index do |controller, scope, value|
		value != "me" ? scope.answered_by(value) : (controller.current_user ? scope.answered_by(controller.current_user.id) : scope.answered_by(0))
	end
	has_scope :unanswered, :type => :boolean, :only => :index
	has_scope :unanswered_by, :only => :index do |controller, scope, value|
		value != "me" ? scope.unanswered_by(value) : (controller.current_user ? scope.unanswered_by(controller.current_user.id) : scope)
	end
	has_scope :q_url, :only => :index do |controller, scope, value|
		value != "current" ? scope.q_url(value) : scope.q_url(controller.session[:questionable_url])
	end
	has_scope :q_sid, :only => :index do |controller, scope, value|
		value != "current" ? scope.q_sid(value) : scope.q_sid(controller.session[:questionable_sid])
	end
	has_scope :q_controller, :only => :index do |controller, scope, value|
		value != "current" ? scope.q_controller(value) : scope.q_controller(controller.session[:questionable_controller])
	end
	has_scope :q_action, :only => :index do |controller, scope, value|
		value != "current" ? scope.q_action(value) : scope.q_action(controller.session[:questionable_action])
	end
	has_scope :order, :only => :index do |controller, scope, value|
		scope.order(value)
	end
	has_scope :page, :only => :index, :default => 1 do |controller, scope, value|
		value.to_i > 0 ? scope.page(value.to_i) : scope.page(1)
	end
	has_scope :per, :only => :index, :default => Proc.new { |c| c.session[:questions_per] ? c.session[:questions_per] : 10 } do |controller, scope, value|
		if controller.request.format != 'html' # API request
			scope.per(value.to_i) if (1..100) === value.to_i
		else
			controller.session[:questions_per] = value.to_i if (1..100) === value.to_i
			controller.session[:questions_per] ? scope.per(controller.session[:questions_per]) : scope.per(10)
		end
	end
	has_scope :select, :only => :index 
	has_scope :uniq, :type => :boolean


	#########################
	# Callbacks. Auth & Permissions via devise & cancan.
	#########################
	before_filter :authenticate_user!, :except => [:index, :show, :random_unanswered]
	before_filter :cuid_to_params, :only => :update
	load_and_authorize_resource

	after_filter :track_view, :only => [:show]


	#########################
	# Modifited Actions
	#########################

	def create
		attrs = {}
		attrs = attrs.merge pick(params[:question], :question, :questionable_url)
		attrs[:questionable_sid]		= session[:questionable_sid]
		attrs[:questionable_controller] = session[:questionable_controller]
		attrs[:questionable_url]   		||= session[:questionable_url]
		attrs[:questionable_action]		= session[:questionable_action]

		@question = current_user.questions.new attrs

		create!
	end

	def random_unanswered
		question = Question.unanswered_by(current_user.id).where("questionable_action = 'show' OR questionable_action = 'index' OR questionable_action = 'home' OR questionable_action = 'about'").order("RANDOM()").first if current_user
		question ||= Question.order("RANDOM()").first 
		redirect_to question.questionable_url
	end

	#########################
	# Protected Methods
	#########################
protected

	def collection
		@questions ||= apply_scopes(end_of_association_chain)
	end

	def cuid_to_params
		params[:question] = add_cuid(params[:question], :cast_vote) if params[:question]
	end

	def track_view
		@question.views.create({user: current_user, ip: remote_ip})
	end
end

app/views/questions/_answer.html.haml
- show_chart = (current_user and (ans = @question.answered_by(current_user.id)))
=content_for :javascripts do
	-if show_chart
		:javascript
			window.onload = function () {
				var y = #{@question.yes_count},
					n = #{@question.no_count},
					d = #{@question.dont_care_count},
					data = [y,n,d],
					cy = '#5bb65b',
					cn = '#da4e49',
					cd = '#999999',
					colors = Array(3);
				if(y >= n && n >= d) {
					colors = [cy, cn, cd];
				}else if(y >= d && d >=n){
					colors = [cy, cd, cn];
				}else if(n >= y && y >= d){
					colors = [cn, cy, cd];
				}else if(n >= d && d >= y){
					colors = [cn, cd, cy];
				}else if(d >= y && y >= n){
					colors = [cd, cy, cn];
				}else if(d >= n && n >= y){
					colors = [cd, cn, cy];
				}
				//
				var r = Raphael("question_pie_chart", 275, 150),
					pie = r.piechart(200, 75, 50, data, { legend: ["%% - Yes", "%% - No", "%% - Don't Care"], legendothers: '0% - Other', legendpos: "west", colors: colors });
				//
				pie.hover(function () {
					this.sector.stop();
					this.sector.scale(1.1, 1.1, this.cx, this.cy);
					//
					if (this.label) {
						this.label[0].stop();
						this.label[0].attr({ r: 7.5 });
						this.label[1].attr({ "font-weight": 800 });
					}
				}, function () {
					this.sector.animate({ transform: 's1 1 ' + this.cx + ' ' + this.cy }, 500, "bounce");
					//
					if (this.label) {
						this.label[0].animate({ r: 5 }, 500, "bounce");
						this.label[1].attr({ "font-weight": 400 });
					}
				});
			};
		

.answer
	-if show_chart
		.row-fluid
			.span12
				%h3.pull-right
					%span.font-thin Your Answer &middot;
					= ans.state.titleize
				#question_pie_chart.pull-right
			
	-else
		.row-fluid
			.span12
				%h3
					Answer
		= form_for( @question.answers.new, :url => "/questions/#{@question.id}/answers" ) do |f|
			.row-fluid
				= text_area_tag 'answer[comment]', nil, :class => "span12", :rows => 3, :placeholder => 'Comment (optional)'	
			.row-fluid
				= label :answer_state_event_ans_, 'yes', :class => 'btn btn span4'
				= radio_button_tag 'answer[state_event]', :ans_yes, false, :onclick => "$('#new_answer').submit();", :class => 'off-screen'
				
				= label :answer_state_event_ans_, 'no', :class => 'btn btn span4'
				= radio_button_tag 'answer[state_event]', :ans_no, false, :onclick => "$('#new_answer').submit();", :class => 'off-screen'
				
				= label :answer_state_event_ans_, "Don't Care", :class => 'btn btn span4', :for => :answer_state_event_ans_dont_care
				= radio_button_tag 'answer[state_event]', :ans_dont_care, false, :onclick => "$('#new_answer').submit();", :class => 'off-screen'

app/views/questions/_question.html.haml
- if question.answered_by current_user
	%tr
		%td
			= link_to truncate(question.question, :length => 30), question, :rel => 'tooltip', 'data-placement' => 'right', 'data-original-title' => question.question
		%td
			= question.answer_count
		%td.color-yes
			= question.yes_count
		%td.color-no
			= question.no_count
		%td.color-dont-care
			= question.dont_care_count
		%td
			= hovercard question.user
		%td
			= time_tag question.created_at, "#{time_ago_in_words(question.created_at)} ago"	
		%td
			= link_to question.questionable_controller, "/questions?q_controller=#{question.questionable_controller}"
		%td
			= link_to question.questionable_action, "/questions?q_action=#{question.questionable_action}"
		%td
			- if question.questionable_sid
				= link_to question.questionable_sid, "/questions?q_sid=#{question.questionable_sid}"
			- else
				none
		%td
			- if question.questionable_url
				= link_to truncate(question.questionable_url, :length => 30), "/questions?q_url=#{question.questionable_url.html_safe}", :rel => 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => question.questionable_url
			- else
				none
		%td
			= question.plusminus
		%td
			-# TODO: make this work. up, right, down arrow for activity up, sideways, down 
			%i.icon-arrow-right
		%td
			%i.icon-check
- else
	-# TODO: add ajax answering right here with Y, N and DC buttons
	%tr
		%td
			= link_to truncate(question.question, :length => 30), question, :rel => 'tooltip', 'data-placement' => 'right', 'data-original-title' => question.question
		%td
		%td
		%td
		%td
		%td
			= hovercard question.user
		%td
			= time_tag question.created_at, "#{time_ago_in_words(question.created_at)} ago"
		%td
			= link_to question.questionable_controller, "/questions?q_controller=#{question.questionable_controller}"
		%td
			= link_to question.questionable_action, "/questions?q_action=#{question.questionable_action}"
		%td
			- if question.questionable_sid
				= link_to question.questionable_sid, "/questions?q_sid=#{question.questionable_sid}"
			- else
				none
		%td
			- if question.questionable_url
				= link_to truncate(question.questionable_url, :length => 30), "/questions?q_url=#{question.questionable_url.html_safe}", :rel => 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => question.questionable_url
			- else
				none
		%td
			= question.plusminus
		%td
			-# TODO: make this work. up, right, down arrow for activity up, sideways, down 
			%i.icon-arrow-right
		%td
			%i.icon-check-empty

app/views/questions/_vote.html.haml
.vote
	- if current_user  
		.up        
			- if current_user.voted_for? @question
				= link_to question_url(@question, question: {cast_vote: {vote: :cancel}}), method: :put, remote: :true do
					%i.icon-chevron-up
			- else
				= link_to question_url(@question, question: {cast_vote: {vote: :for}}), method: :put, remote: :true do
					%i.icon-chevron-up.opacity4
			&nbsp;
		
		.count
			= @question.plusminus

		.down
			- if current_user.voted_against? @question            
				= link_to question_url(@question, question: {cast_vote: {vote: :cancel}}), method: :put, remote: :true do
					%i.icon-chevron-down
			- else
				= link_to question_url(@question, question: {cast_vote: {vote: :against}}), method: :put, remote: :true do
					%i.icon-chevron-down.opacity4
			&nbsp;

	- else  
		.up       
			= link_to question_url(@question, question: {cast_vote: {vote: :for}}), method: :put do
				%i.icon-chevron-up.opacity4
			&nbsp;
		
		.count
			= @question.plusminus

		.down
			= link_to question_url(@question, question: {cast_vote: {vote: :against}}), method: :put do
				%i.icon-chevron-down.opacity4
			&nbsp;

app/views/questions/index.html.haml
-content_for :title do "questions" end

.container-fluid
	.content
		#questions
			.page-header
				%h1 
					Questions
			.row-fluid
				.span12
					.pull-right
						-# TODO make a session variable for question_per and use it to set the default if per is ever changed
						-# remove per from query string and optionally add an ampersand
						- query_string = request.query_string.gsub(/(&per|per)=([0-9][0-9][0-9]|[0-9][0-9]|[0-9])/, '')
						- query_string += "\&" unless query_string.blank?
						= link_to 10, "/questions?#{query_string}per=10"
						&middot;
						= link_to 30, "/questions?#{query_string}per=30"
					.pull-right
						= "? #{request.query_string.split('&').join(' .. ')}"
						&middot;&nbsp;
					%table.table
						%tr
							%th Question
							%th{rel: 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => "answer count"} ANS
							%th{rel: 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => "yes count"} Y
							%th{rel: 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => "no count"} N
							%th{rel: 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => "don't care count"} DC
							%th Asked By
							%th Date
							%th Controller
							%th Action
							%th Id
							%th Url
							%th Votes
							%th Activity
							%th{rel: 'tooltip', 'data-placement' => 'bottom', 'data-original-title' => "answered by me"}
								- if current_user
									= image_tag current_user.avatar.image.small.url, width: 18, height: 18, class: 'circle'
								- else
									%i.icon-user 
						= render @questions

					= paginate @questions

app/views/questions/index.js.erb
$('#questions table').append('<%= j render(@questions) %>');
<% if @questions.current_page < @questions.num_pages %>
	$('#questions .pagination').replaceWith('<%= j paginate(@questions) %>');
<% else %>
	$('#questions .pagination').html('<li class="active"><a href="#">No more questions to load</a></li>');
<% end %>

app/views/questions/show.html.haml
-content_for :title do "#{@question.question}" end

.container-fluid
	.content
		#question
			.page-header
				.row-fluid
					.span1
						= render 'vote'
					.span7  
						%h2
							= @question.question
						%br
						%p
							Asked by
							= hovercard @question.user
							= time_tag @question.created_at, "#{time_ago_in_words(@question.created_at)} ago"
					.span4
						= render 'answer'
			- if current_user and @question.answered_by(current_user.id)
				.row-fluid
					.span5
						.sub-header 
							%h2 
								.pull-right.font-thin
									== #{@question.yes_count}:Y &nbsp; #{@question.no_count}:N &nbsp; #{@question.dont_care_count}:DC
								= pluralize(@question.answer_count, "Answer")
						%table.table
							- @question.answers.each do |answer|
								%tr
									%td
										= answer.state.titleize
									%td
										= hovercard answer.user
									%td
										= time_tag answer.created_at, "#{time_ago_in_words(answer.created_at)} ago"
					.span7
						= render 'comments/comments', commentable: @question

app/views/questions/update.js.erb
$('#question .vote [rel*=tooltip]').tooltip('hide');
$('#question .vote').replaceWith('<%= escape_javascript render("vote") %>');
$('#question .vote [rel*=tooltip]').tooltip();