config/routes.rb
Ananta::Application.routes.draw do

	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config

	post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
	
	resources :sessions, :only => [:index]

	resources :comments, :only => [:index, :show, :create, :edit, :update, :destroy]
	resources :locations, :only => [:create, :update]

	resources :questions, :only => [:index, :show, :create, :update] do
		collection do
			get 'page/:page', :action => :index
			get 'random_unanswered'
		end
		resources :answers, :only => [:index, :show, :create, :update] do
			resources :comments, :only => [:create]
		end
	end

	resources :project_memberships, :only => [] do
		member do
			post 'accept'
			post 'reject'
		end
	end

	resources :projects, :only => [:index, :show] do
		collection do
			get 'page/:page', :action => :index
			get 'random'
		end
		resources :comments, :only => [:index]
	end

	resources :images, :only => [:create, :update, :destroy]

	match '/render_nav' => 'users#render_nav' # ujs render user_nav. generally called after ajax login
	resources :users, :only => [:index] do
		collection do
			get 'random'
		end
	end
	devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations', :sessions => 'users/sessions' }
	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
		get '/register' => 'devise/registrations#new'
	end

	match '/me' => 'pages#me' 
	match '/tb' => 'pages#tb' if Rails.env == 'development'
	match '/about' => 'pages#about'
	match '/robots.txt' => 'pages#robots'

	root :to => 'pages#home'

	resources :profiles, :path => '' do
		member do
			get :edit_location
		end
	end
	resources :users, :path => '', :only => [] do
		resources :projects, :path => '', :except => [:index] do
			member do
				post "join"
				post "leave"
			end
		end
	end

	# See how all your routes lay out with "rake routes"
end

app/models/comment.rb
# One or two line description of what the model represents
#
#
# require File.join(Rails.root, 'lib/ananta/vote')

class Comment < ActiveRecord::Base

	#########################
	# Callbacks & Misc method calls (e.g. devise for, acts_as_whatever )
	#########################
	include Ananta::Vote
	include Twitter::Extractor
	include Rails.application.routes.url_helpers
	
	acts_as_voteable
	acts_as_ordered_taggable

	# Versioning
	has_paper_trail

	after_save :extract_mentions
	after_save :extract_tags
	after_create :notify_commentable


	#########################
	# Setup attributes (reader, accessible, protected)
	#########################
	#attr_reader
	#attr_accessor
	# Make sure all controllers that create comments define user_id = current_user.id
	attr_accessible :comment, :commentable_id, :commentable_type, :cast_vote, :on => :create


	#########################
	# Associations
	#########################
	belongs_to :user
	belongs_to :commentable, :polymorphic => true
	has_many :comments, :as => :commentable, :dependent => :destroy
	has_many :notifications, :as => :notifiable, :dependent => :destroy


	#########################
	# Validations
	#########################
	# validates :user_id, :presence => true
	# validates :commentable_id, :presence => true
	# validates :commentable_type, :presence => true
	validates :comment, :presence => true, :length => { :in => 1..65535 }


	#########################
	# Scopes
	#########################
	default_scope :order => 'created_at asc'

	#scope :red, where(:color => 'red')


	#########################
	# Public Class Methods ( def self.method_name )
	#########################

	## One line description
	## maybe two
	#def self.my_method
	#
	#end


	#########################
	# Public Instance Methods ( def method_name )
	#########################

	def editors
		editors = [self.user]
		editors
	end

	def path
		case self.commentable_type
		when "Project"
			commentable_path = user_project_path(self.commentable.user, self.commentable)
		when "Answer"
			commentable_path = question_path(self.commentable.question)
		else
			commentable_path = nil
		end
		
		if commentable_path
			"#{commentable_url}#comment_#{self.id}"
		else
			nil
		end
	end


	#########################
	# Protected Methods
	#########################
protected

	def extract_mentions
		if comment_changed?
			old_usernames = extract_mentioned_screen_names(changes[:comment][0]).uniq
			new_usernames = extract_mentioned_screen_names(changes[:comment][1]).uniq
			added_usernames = new_usernames - old_usernames
			added_usernames.each do |username|
				if u = User.find_by_username(username)
					u.notifications.create(notifiable: self, message: "<b>#{self.user.username}</b> mentioned you in a comment", url: self.path) # TODO: maybe specify the url on the comment explicitly and then copy it here?
				end
			end
		end
	end

	def extract_tags
		if comment_changed?
			tags = extract_hashtags(self.comment).uniq
			self.tag_list = tags.reverse.join(',')
		end
	end

	def notify_commentable
		self.commentable.user.notifications.create(notifiable: self, message: "<b>#{self.user.username}</b> commented on your #{self.commentable_type.downcase}", url: self.path) # TODO: maybe specify the url on the comment explicitly and then copy it here?
	end


	#########################
	# Private Methods
	#########################
private

	# Same as Public Instance Methods


end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
	respond_to :js, :html, :json
	belongs_to :answer, :comment, :project, :user, :polymorphic => true, :optional => true
	actions :index, :show, :create, :edit, :update, :destroy

	before_filter :authenticate_user!, :except => [:index, :show]
	before_filter :cuid_to_params, :only => :update # TODO: REFACTOR: this is complicated
	load_and_authorize_resource

	def create
		@comment = current_user.comments.new params[:comment]
		create!
	end

protected

	def collection
		@comments = end_of_association_chain.reorder(sort_column + " " + sort_direction)
	end

	def cuid_to_params
		params[:comment] = add_cuid(params[:comment], :cast_vote) if params[:comment]
	end

private

	def sort_column
		session["comment_sort_attribute"] = params[:sort] if params[:sort]
		Comment.column_names.include?(session["comment_sort_attribute"]) ? session["comment_sort_attribute"] : "created_at"
	end

	def sort_direction
		session["comment_sort_direction"] = params[:direction] if params[:direction]
		%w[asc desc].include?(session["comment_sort_direction"]) ? session["comment_sort_direction"] : "asc"
	end

end

app/views/comments/_comment.html.haml
- comment_url = CGI.escape "#{root_url[0...-1]}#{request.path}#comment_#{comment.id}"
= div_for comment, class: "#{current_user == comment.user ? 'by-me' : ''} #{comment.user == comment.commentable.user ? 'by-commentable' : ''}" do
	.row-fluid
		.span12.comment-content
			.comment-avatar
				= link_to comment.user.profile do
					= image_tag comment.user.avatar.image.small.url, :class => 'circle'

			.comment-text
				.arrow-left
					.mini-arrow-left
				.inner
					.row-fluid.top
						.span12
							= hovercard comment.user
							- if comment.user == comment.commentable.user
								&middot;
								%i.icon-wrench.display-inline-block
							
					.row-fluid.middle
						.span12
							= tagged_markdown comment.comment

					.row-fluid.bottom
						.span12
							= render 'comments/vote', comment: comment
							&middot;
							= link_to "Reply", "#"
							- if can?(:destroy, comment)
								&middot;
								= link_to "Edit", "/comments/#{comment.id}/edit", remote: true
								&middot;
								= link_to "Delete", comment, method: :delete, remote: true, confirm: "Are you sure?"
							&middot;
							%h6.display-inline-block= "#{distance_of_time_in_words_to_now comment.created_at} ago"
							- if can?(:destroy, comment)
								&middot;
								%p.display-inline-block= "(#{distance_of_time_in_words(comment.created_at + 15.minutes - DateTime.now.utc)} left to make changes)"
							&middot;
							%a.opacity5{:href => "http://api.addthis.com/oexchange/0.8/forward/facebook/offer?pco=tbxnj-1.0&url=#{comment_url}&pubid=ra-4e07edfe1206c99f", :target => "_blank"}
								%img{:alt => "Facebook", :border => "0", :src => "http://cache.addthiscdn.com/icons/v1/thumbs/facebook.gif"}/
							%a.opacity5{:href => "http://api.addthis.com/oexchange/0.8/forward/twitter/offer?pco=tbxnj-1.0&url=#{comment_url}&pubid=ra-4e07edfe1206c99f", :target => "_blank"}
								%img{:alt => "Twitter", :border => "0", :src => "http://cache.addthiscdn.com/icons/v1/thumbs/twitter.gif"}/
							%a.opacity5{:href => "http://api.addthis.com/oexchange/0.8/forward/email/offer?pco=tbxnj-1.0&url=#{comment_url}&pubid=ra-4e07edfe1206c99f", :target => "_blank"}
								%img{:alt => "Email", :border => "0", :src => "http://cache.addthiscdn.com/icons/v1/thumbs/email.gif"}/

	- unless comment.comments.blank?
		.row-fluid
			.span1
			.span11
				= render 'comments/comments', commentable: comment

app/views/comments/_comments.html.haml
- comments = @comments 
- comments ||= commentable.comments

%div{ id: "#{commentable.class.to_s.downcase}_#{commentable.id}_comments"}
	
	- unless commentable.class.to_s == 'Comment'
		%h6 
			= pluralize(comments.count, "Comment")
			%i.icon-comments
			.pull-right
				sort by
				&middot; 
				= toggle_sort 'created_at', 'date', send("#{commentable.class.to_s.downcase}_comments_path", commentable), 'comment'
				-#
					&middot;
					= toggle_sort 'vote_count', 'votes', send("#{commentable.class.to_s.downcase}_comments_path", commentable), 'comment'
					
	.comments
		- comments.each do |comment|
			= render 'comments/comment', comment: comment

	- unless commentable.class.to_s == 'Comment'
		= render 'comments/form', comment: commentable.comments.new

app/views/comments/_form.html.haml
.comment.by-me
	.row-fluid
		.span12.comment-content
			.comment-avatar
				- if current_user
					= link_to current_user.profile do
						= image_tag current_user.avatar.image.small.url, :class => 'circle'
				- else
					= image_tag Profile.new.avatar.image.small.url, :class => 'circle'
			.comment-text
				.arrow-left
					.mini-arrow-left
				.inner
					= simple_form_for comment, (current_user ? {remote: true} : {remote: false}) do |f|
						= f.hidden_field :commentable_id, value: comment.commentable_id
						= f.hidden_field :commentable_type, value: comment.commentable_type
						.row-fluid.top
							.span12
								%i.pull-right.icon-info-sign{style: 'font-size: 18px; color: #999;', rel: 'popover', 'data-placement' => 'top', 'data-trigger' => 'hover', 'data-title' => 'Options', 'data-content' => '@mentions, #tags, markdown'}
								- if current_user
									= hovercard current_user
									- if current_user == comment.commentable.user
										&middot;
										%i.icon-wrench
								- else
									me
								
						.row-fluid.middle
							.span12
								= f.input :comment, label: false, input_html: { class: 'span12', rows: "1", placeholder: "New comment", style: 'margin: 0;' }
									
						.row-fluid.bottom{style: "margin-bottom: -11px; margin-top: 4px;"}
							.span12
								- if comment.id
									= f.button :submit, 'Save Comment', :class => 'btn-success btn-large'
								- else
									= f.button :submit, 'Post Comment', :class => 'btn-success btn-large'
								&middot;
								%h6.display-inline-block= "right now"

app/views/comments/_vote.html.haml
%span.comment-vote
    - if current_user  
        %span.count
            = comment.votes_for
        %span.up        
            - if current_user.voted_for? comment
                = link_to comment_url(comment, comment: {cast_vote: {vote: :cancel}}), method: :put, remote: :true do
                    %i.icon-arrow-up.color-yes
            - else
                = link_to comment_url(comment, comment: {cast_vote: {vote: :for}}), method: :put, remote: :true do
                    %i.icon-arrow-up.color-dont-care
        &middot;
        %span.down       
            - if current_user.voted_against? comment
                = link_to comment_url(comment, comment: {cast_vote: {vote: :cancel}}), method: :put, remote: :true do
                    %i.icon-flag.color-no
            - else
                = link_to comment_url(comment, comment: {cast_vote: {vote: :against}}), method: :put, remote: :true do
                    %i.icon-flag.color-dont-care

    - else 
        %span.count
            = comment.votes_for
        %span.up       
            = link_to comment_url(comment, comment: {cast_vote: {vote: :for}}), method: :put do
                %i.icon-arrow-up.color-dont-care
        &middot;
        %span.down       
            = link_to comment_url(comment, comment: {cast_vote: {vote: :against}}), method: :put do
                %i.icon-flag.color-dont-care

app/views/comments/create.js.erb
$('#<%= @comment.commentable.class.to_s.downcase %>_<%= @comment.commentable.id %>_comments>.comments').append('<%= escape_javascript render("comments/comment", comment: @comment) %>');
$('#new_comment textarea').val('').css("height", '').focus();

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$('#comment_<%= @comment.id %>').html('<%= escape_javascript render("comments/form", comment: @comment) %>');
$('#comment_<%= @comment.id %> textarea').autosize();

app/views/comments/index.js.erb
$("#<%= @comments.first.commentable.class.to_s.downcase %>_<%= @comments.first.commentable.id %>_comments").replaceWith('<%= escape_javascript render("comments/comments", commentable: @comments.first.commentable) %>');
window.initUI();

app/views/comments/update.js.erb
$('#comment_<%= @comment.id %>').replaceWith('<%= escape_javascript render("comments/comment", comment: @comment) %>');