config/routes.rb
Ananta::Application.routes.draw do

	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config

	post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
	
	resources :sessions, :only => [:index]

	resources :comments, :only => [:index, :show, :create, :edit, :update, :destroy]
	resources :locations, :only => [:create, :update]

	resources :questions, :only => [:index, :show, :create, :update] do
		collection do
			get 'page/:page', :action => :index
			get 'random_unanswered'
		end
		resources :answers, :only => [:index, :show, :create, :update] do
			resources :comments, :only => [:create]
		end
	end

	resources :project_memberships, :only => [] do
		member do
			post 'accept'
			post 'reject'
		end
	end

	resources :projects, :only => [:index, :show] do
		collection do
			get 'page/:page', :action => :index
			get 'random'
		end
		resources :comments, :only => [:index]
	end

	resources :images, :only => [:create, :update, :destroy]

	match '/render_nav' => 'users#render_nav' # ujs render user_nav. generally called after ajax login
	resources :users, :only => [:index] do
		collection do
			get 'random'
		end
	end
	devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations', :sessions => 'users/sessions' }
	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
		get '/register' => 'devise/registrations#new'
	end

	match '/me' => 'pages#me' 
	match '/tb' => 'pages#tb' if Rails.env == 'development'
	match '/about' => 'pages#about'
	match '/robots.txt' => 'pages#robots'

	root :to => 'pages#home'

	resources :profiles, :path => '' do
		member do
			get :edit_location
		end
	end
	resources :users, :path => '', :only => [] do
		resources :projects, :path => '', :except => [:index] do
			member do
				post "join"
				post "leave"
			end
		end
	end

	# See how all your routes lay out with "rake routes"
end

app/models/project.rb
# This canonical record is the foundation of the site
# Everything revolves around projects and making them better
#

# require File.join(Rails.root, 'lib/ananta/vote')

class Project < ActiveRecord::Base
  #########################
  # Callbacks & Misc method calls (e.g. devise for, acts_as_whatever )
  #########################
  include Ananta::Vote

  has_paper_trail # TODO: add tags to versioning, exclude name (i.e. friendly_id) from version
  acts_as_ordered_taggable_on :tags
  acts_as_voteable

  # Project state machine
  # TODO: Remove State Machine from the whole app.
  state_machine :initial => :draft do

    event :validate do # Is this project worth pursuing?
      transition :draft => :validating
    end

    # event :learn do # What do I need to know about this project to make it a success?
    #   transition :validating => :learning
    # end

    event :design do # Who do I need on my team? What is our plan? What are our expectations?
      transition :validating => :designing 
    end

    event :build do # If communications is key, are we communicating enough?
      transition :designing => :building
    end

    event :check_complete do
      transition :building => :completing
    end

    event :not_complete do
      transition :completing => :building
    end

    event :complete do
      transition :completing => :complete
    end

    event :kill do
      transition [:draft, :validating, :learning, :designing, :building, :completing] => :killed
    end
  end

  # Geocoder
  geocoded_by nil, :latitude => :lat, :longitude => :lng

  # Callbacks
  after_create :after_create


  #########################
  # Setup attributes (reader, accessible, protected)
  #########################
  # attr_reader :cast_vote
  attr_accessor :tag_tokens
  attr_accessible :name, :description, :state_event, :tag_tokens, :cast_vote


  #########################
  # Associations
  #########################
  extend FriendlyId
  friendly_id :name, :use => :slugged

  belongs_to :user,            :counter_cache => true
  has_many   :project_memberships, :dependent => :destroy
  has_many   :pending_memberships, :source => :project_memberships, :class_name => 'ProjectMembership', :conditions => ["state = ?", "pending"]
  has_many   :pending_members, :source => :user, :class_name => 'User', :through => :project_memberships, :conditions => ["state = ?", "pending"]
  has_many   :members,         :source => :user, :class_name => 'User', :through => :project_memberships, :conditions => ["state = ?", "accepted"]
  has_many   :participants,    :through => :comments, :source => :user, :class_name => 'User', :uniq => true
  has_one    :location,        :as => :locatable, :dependent => :destroy
  has_many   :images,          :as => :imageable, :dependent => :destroy
  has_many   :avatars,         :as => :imageable, :source => :images, :class_name => "Image", :conditions => ["image_type = ?", "avatar"]
  has_many   :pictures,        :as => :imageable, :source => :images, :class_name => "Image", :conditions => ["image_type = ?", "picture"]
  has_many   :views,           :as => :viewable,  :dependent => :destroy
  has_many   :comments,        :as => :commentable, :dependent => :destroy
  has_many   :notifications,   :as => :notifiable, :dependent => :destroy

  accepts_nested_attributes_for :location


  #########################
  # Validations
  #########################
  validates :name,
    :uniqueness => {:scope => :user_id, :message => "cannot be the same as one of your other projects"},
    :length => { :minimum => 3, :maximum => 141, :too_short => "is too short, please say a little more", :too_long => "is too long, please say a little less (141 characters max)" } # TODO: find out why this causes problems with migrations
  before_destroy :validate_not_last_project


  #########################
  # Scopes
  #########################
  # scope :red, where(:color => 'red')


  #########################
  # Public Class Methods ( def self.method_name )
  #########################

  ## One line description
  ## maybe two
  #def self.my_method
  #
  #end


  #########################
  # Public Instance Methods ( def method_name )
  #########################

  # Current avatar Image
  def avatar
    current_avatar = avatars.last
    current_avatar ? current_avatar : Image.new(:imageable => self, :image_type => 'avatar')
  end
  
  # Helper for token_autocomplete
  def tag_tokens= ids
    self.tag_list = ids
  end

  # The users who may modify this model
  def editors
    editors = [self.user]
    editors
  end

  def energy
    3
  end

  def followers
    self.votes.where(vote:true, voter_type:'User').map{|v| v.voter}
  end


  #########################
  # Protected Methods
  #########################
  protected
  

  #########################
  # Private Methods
  #########################
  private

  def validate_not_last_project
    if self.user.projects.count > 1
      true
    else
      errors.add(:project, "is your last. You cannot delete this project until you create another one.")
      false
    end
  end

  def after_create
    self.user.vote_exclusively_for(self)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
	#########################
	# Config via inherited_resources https://github.com/josevalim/inherited_resources 
	#########################
	respond_to :js, :html, :json
	belongs_to :user, :optional => true
	

	#########################
	# Scopes via has_scope https://github.com/plataformatec/has_scope
	#########################
	has_scope :order, :only => :index do |controller, scope, value|
		case value
		when 'r'
			scope.order("RANDOM()")
		else
			scope.order(value)
		end
	end
	has_scope :page, :only => :index, :default => 1 do |controller, scope, value|
		value.to_i > 0 ? scope.page(value.to_i) : scope.page(1)
	end
	has_scope :per, :only => :index, :default => Proc.new { |c| c.session[:projects_per] ? c.session[:projects_per] : 10 } do |controller, scope, value|
		if controller.request.format != 'html' # API request
			scope.per(value.to_i) if (1..100) === value.to_i
		else
			controller.session[:projects_per] = value.to_i if (1..100) === value.to_i
			controller.session[:projects_per] ? scope.per(controller.session[:projects_per]) : scope.per(10)
		end
	end


	#########################
	# Callbacks. Auth & Permissions via devise & cancan.
	#########################
	before_filter :authenticate_user!, :except => [:index, :show, :random]
	before_filter :cuid_to_params, :only => :update # TODO: REFACTOR: this is complicated
	load_and_authorize_resource

	after_filter :track_view, :only => [:show]


	#########################
	# Modifited Actions
	#########################

	def new
		populate_tags @project, :tags
		new!
	end

	def create
		populate_tags @project, :tags
		@project.location ||= @user.location.dup rescue nil
		create! do |success, failure|
			success.html do 
				# flash[:notice] = "Successfully created project. #{undo_link}" # TODO: enable undo/redo eventually
				redirect_to user_project_url(@user, @project)
			end
			success.json do
				flash[:notice] = "Project created."
			end
		end
	end

	def edit
		populate_tags @project, :tags
		edit!
	end

	def update
		populate_tags @project, :tags
		params[:project] ||= {}
		params[:project] = pick(params[:project], :name, :description, :state_event, :tag_tokens, :cast_vote)
		update! do |success, failure|
			success.html do 
				# flash[:notice] = "Successfully updated project. #{undo_link}"
				redirect_to user_project_url(@user, @project)
			end
			success.json do
				flash[:notice] = "Project update."
			end
		end
	end

	def destroy
		populate_tags @project, :tags
		destroy! do |success, failure|
			success.html do 
				# flash[:notice] = "Successfully deleted project. #{undo_link}"
				redirect_to profile_url(@user)
			end
		end
	end

	def random
		@project = Project.order("RANDOM()").first
		redirect_to([@project.user, @project])
	end

	def join
		membership = @project.project_memberships.new
		membership.update_attribute(:user, current_user)
		flash[:notice] = "Join request sent. You will be notified when it is accepted or rejected."
		redirect_to user_project_url(@project.user, @project)
	end

	def leave
		membership = @project.project_memberships.where(user_id: current_user.id).first
		if membership and membership.destroy
			@project.user.notifications.create(notifiable: @project, message: "<b>#{membership.user.username}</b> has left <b>#{@project.name}</b>", url: "#{user_project_url(@project.user, @project)}#project-members")
			flash[:notice] = "You have left this project."
		else
			flash[:error] = "We could not remove you from this project."
		end
		redirect_to user_project_url(@project.user, @project)
	end

	#########################
	# Protected Methods
	#########################
protected

	def collection
		@projects ||= apply_scopes(end_of_association_chain)
	end

	def cuid_to_params
		params[:project] = add_cuid(params[:project], :cast_vote) if params[:project]
	end

	# def undo_link
	#	view_context.link_to("undo", revert_version_path(@project.versions.scoped.last), :method => :post)
	# end

	def track_view
		@project.views.create({user: current_user, ip: remote_ip})
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
=content_for :javascripts do
	:javascript
		//
		window.project_tags = #{raw  @tags['tags'].to_json}
		//
		window.selected_project_tags = #{raw @selected_tags['tags'].to_json}
		//
		$(document).ready(function() {
			$('#project_tag_tokens').tokenInput(window.project_tags, { theme : 'facebook', preventDuplicates: true, tokenLimit: 100, prePopulate: window.selected_project_tags, createTokenFromQuery: true } );
		});
		
.row-fluid
	.span12
		= simple_form_for [@user, @project], :html => {:class => "form-horizontal"} do |f|
			= f.input :name, input_html: {class: :span4}
			%br
			-if params[:action] == 'edit'

				= render 'images/filepicker', image: @project.avatar, element: '#project_avatar', ratio: '16:9'
				= f.input :avatar do
					#project_avatar.span6
						= image_tag(@project.avatar.image.large.url)
						.btn.btn-info.choose-file Choose Image
				%br
			= f.input :description, input_html: {rows: 5, class: :span4}
			%br
			= f.input :tag_tokens, label: "Tags"
			%br
			.form-actions
				= f.button :submit, :class => 'btn-primary'
				= link_to I18n.t('cancel'), :back, :class => 'btn btn-danger'

app/views/projects/_join_link.html.haml
- if current_user
	- if current_user.member?(project)
		= link_to "Leave", leave_user_project_path(project.user, project), method: :post, class: 'btn btn-danger btn-mini', confirm: 'Are you sure?'
	- elsif current_user.pending_member?(project)
		= link_to "Cancel Join Request", leave_user_project_path(project.user, project), method: :post, class: 'btn btn-danger btn-mini', confirm: 'Are you sure?'
	- elsif current_user != project.user
		= link_to "Join", join_user_project_path(project.user, project), method: :post, class: 'btn btn-success'

app/views/projects/_join_requests.html.haml
- if current_user and current_user.editor? project
    - unless project.pending_memberships.blank?
        .row-fluid{style:"background-color: #eee;"}
            .span12
                .row-fluid
                    .span12
                        %h4
                            Pending Members
                        %hr
                - project.pending_memberships.each do |membership|
                    .row-fluid
                        .span12
                            %h3= hovercard membership.user
                    .row-fluid
                        .span12 
                            = link_to "Accept", accept_project_membership_path(membership), method: :post, class: 'btn btn-success'
                            = link_to "Reject", reject_project_membership_path(membership), method: :post, class: 'btn btn-danger'
                            %hr

app/views/projects/_project.html.haml
.project
	.row-fluid
		.span12.image
			= link_to user_projects_path([project.user, project]) do image_tag project.avatar.image.medium end
	.row-fluid
		.span12.info
			.row-fluid
				.span12
					%h2.name= link_to project.name, user_projects_path([project.user, project])
			.row-fluid
				.span12
					%p.state= project.state
			.row-fluid
				.span12
					%p.description= project.description
			.row-fluid
				.span12.bottom
					.row-fluid
						.span12.tags
							= list_tags project.tags
					.row-fluid
						.span3.energy.center
							%strong= project.energy
							%b.hidden-desktop
							%i.icon-bolt
							%p.visible-desktop= project.energy == 1 ? 'volt' : 'volts'
						.span3.views.center
							%strong= project.view_count
							%b.hidden-desktop
							%i.icon-eye-open
							%p.visible-desktop= project.view_count == 1 ? 'view' : 'views'
						.span3.lovers.center
							%strong= project.votes_for
							%b.hidden-desktop
							%i.icon-star
							%p.visible-desktop= project.votes_for == 1 ? 'star' : 'stars'
						.span3.user
							= link_to project.user.profile do
								= image_tag project.user.avatar.image.small, class: 'circle', alt: project.user.username, title: project.user.username

app/views/projects/_thumbnail.html.haml
%li.span3
	.thumbnail
		= link_to user_projects_path([project.user, project]) do image_tag project.avatar.image.medium end
		%h2.name= link_to project.name, user_projects_path([project.user, project])
		%p.description= project.description
		.tags= list_tags project.tags
		%p.state= project.state
		%p.user= hovercard project.user

app/views/projects/_vote.html.haml
.project-vote
    .btn-toolbar
        - if current_user
            .btn-group            
                - if current_user.voted_for? @project
                    = link_to pluralize(@project.votes_for, 'Star'), "#", class: 'btn'
                    = link_to user_project_url(@project.user, @project, project: {cast_vote: {vote: :cancel}}), method: :put, remote: :true, class: 'btn btn-warning', rel: :tooltip, title: 'unstar', 'data-placement' => 'top' do
                        %i.icon-star
                - else
                    .btn
                        = pluralize(@project.votes_for, 'Star')
                    = link_to user_project_url(@project.user, @project, project: {cast_vote: {vote: :for}}), method: :put, remote: :true, class: 'btn', rel: 'tooltip', title: 'star', 'data-placement' => 'top' do
                        %i.icon-star-empty.opacity4
            .btn-group
                - if current_user.voted_against? @project            
                    = link_to user_project_url(@project.user, @project, project: {cast_vote: {vote: :cancel}}), method: :put, remote: :true, class: 'btn btn-danger', rel: 'tooltip', title: 'unflag', 'data-placement' => 'top' do
                        %i.icon-flag
                - else
                    = link_to user_project_url(@project.user, @project, project: {cast_vote: {vote: :against}}), method: :put, remote: :true, class: 'btn', rel: 'tooltip', title: 'flag as inappropriate', 'data-placement' => 'top' do
                        %i.icon-flag.opacity4
        - else
            .btn-group 
                .btn
                    = pluralize(@project.votes_for, 'Star')

app/views/projects/_votes.html.haml
#votes
    .btn-toolbar
        - if current_user
            .btn-group            
                - if current_user.voted_for? @project
                    = link_to pluralize(@project.votes_for, 'Lover'), "#", class: 'btn', rel: :tooltip, title: 'including you!', 'data-placement' => 'bottom'
                    = link_to user_project_url(@user, @project, project: {vote: :cancel}), method: :put, remote: :true, class: 'btn btn-success', rel: :tooltip, title: 'unlove', 'data-placement' => 'bottom' do
                        %i.icon-heart
                - else
                    .btn
                        = pluralize(@project.votes_for, 'Lover')
                    = link_to user_project_url(@user, @project, project: {vote: :for}), method: :put, remote: :true, class: 'btn', rel: 'tooltip', title: 'love', 'data-placement' => 'bottom' do
                        %i.icon-heart.opacity4
            .btn-group
                - if current_user.voted_against? @project            
                    = link_to user_project_url(@user, @project, project: {vote: :cancel}), method: :put, remote: :true, class: 'btn btn-warning', rel: 'tooltip', title: 'unflag', 'data-placement' => 'bottom' do
                        %i.icon-flag
                - else
                    = link_to user_project_url(@user, @project, project: {vote: :against}), method: :put, remote: :true, class: 'btn', rel: 'tooltip', title: 'flag', 'data-placement' => 'bottom' do
                        %i.icon-flag.opacity4
        - else
            .btn-group 
                .btn
                    = pluralize(@project.votes_for, 'Lover')

app/views/projects/edit.html.haml
.container-fluid
	.content
		.page-header
			%h1 Editing project

		= render 'form'

		= link_to "Delete this project", user_project_path(@user, @project), :method => :delete

app/views/projects/index.html.haml
-content_for :title do "projects" end

=content_for :javascripts do
	:javascript
		$.Isotope.prototype._getCenteredMasonryColumns = function() {
			this.width = this.element.width();
			
			var parentWidth = this.element.parent().width();
			
										// i.e. options.masonry && options.masonry.columnWidth
			var colW = this.options.masonry && this.options.masonry.columnWidth ||
										// or use the size of the first item
										this.$filteredAtoms.outerWidth(true) ||
										// if there's no items, use size of container
										parentWidth;
			
			var cols = Math.floor( parentWidth / colW );
			cols = Math.max( cols, 1 );
			//
			// i.e. this.masonry.cols = ....
			this.masonry.cols = cols;
			// i.e. this.masonry.columnWidth = ...
			this.masonry.columnWidth = colW;
		};
		//
		$.Isotope.prototype._masonryReset = function() {
			// layout-specific props
			this.masonry = {};
			// FIXME shouldn't have to call this again
			this._getCenteredMasonryColumns();
			var i = this.masonry.cols;
			this.masonry.colYs = [];
			while (i--) {
				this.masonry.colYs.push( 0 );
			}
		};
		//
		$.Isotope.prototype._masonryResizeChanged = function() {
			var prevColCount = this.masonry.cols;
			// get updated colCount
			this._getCenteredMasonryColumns();
			return ( this.masonry.cols !== prevColCount );
		};
		//
		$.Isotope.prototype._masonryGetContainerSize = function() {
			var unusedCols = 0,
					i = this.masonry.cols;
			// count unused columns
			while ( --i ) {
				if ( this.masonry.colYs[i] !== 0 ) {
					break;
				}
				unusedCols++;
			}
			
			return {
						height : Math.max.apply( Math, this.masonry.colYs ),
						// fit container to columns that have been used;
						width : (this.masonry.cols - unusedCols) * this.masonry.columnWidth
					};
		};

	:coffeescript
		$('#project-grid').isotope(
			itemSelector: '.project'
			# layoutMode:	'fitRows'
			masonry:
				columnWidth: 304
			animationOptions:
				duration: 750
				easing: 'linear'
				queue: false
		)

.container-fluid
	.content
		#projects
			.page-header
				%h1.center 
					Explore Projects
			.row-fluid
				.span12
					#project-grid.center
						= render @projects
					= paginate @projects


		=# link_to 'New Project', new_project_path

app/views/projects/index.js.erb
$('#project-grid').isotope('insert', $('<%= j render(@projects) %>'));
<% if @projects.current_page < @projects.num_pages %>
	$('#projects .pagination').replaceWith('<%= j paginate(@projects) %>');
<% else %>
	$('#projects .pagination').html('<li class="active"><a href="#">No more projects to load</a></li>');
<% end %>

app/views/projects/new.html.haml
.container-fluid
	.content
		.page-header
			%h1 New project

		= render 'form'

app/views/projects/show.html.haml
-content_for :title do "#{@project.name}" end

#project
	= div_for @project, class: 'project' do
		.container-fluid
			.row-fluid
				.span12.page-header
					- if can? :update, @project
						.row-fluid
							.span12
								.pull-right
									= link_to edit_user_project_path(@project.user, @project) do
										Edit
										%i.icon-edit
					.row-fluid
						.span12
							%h1.center 
								= link_to @project.name, user_project_path(@project.user, @project)
					.row-fluid
						.span12
							%p.center
								by
								= link_to @project.user.username, profile_path(@project.user.profile)
							
		.container-fluid
			.content.box-shadow
				.row-fluid
					.span12
						.container-fluid
							.row-fluid
								.span8
									.row-fluid
										.span12
											= image_tag(@project.avatar.image.large.url)
											%hr
									.row-fluid
										.span12
											.row-fluid
												.span12
													.pull-right.display-inline-block= render "vote"
													.hidden-phone.opacity5.display-inline-block.addthis_toolbox.addthis_default_style.addthis_32x32_style{style: 'width: 333px; margin-top: 13px;'}
														%a.addthis_button_facebook
														%a.addthis_button_twitter
														%a.addthis_button_pinterest
														%a.addthis_button_stumbleupon
														%a.addthis_button_reddit
														%a.addthis_button_email
														%a.addthis_button_compact
														%a.addthis_counter.addthis_bubble_style
													.visible-phone.opacity5.display-inline-block.addthis_toolbox.addthis_default_style.addthis_32x32_style{style: 'width: 300px; margin-top: 13px;'}
														%a.addthis_button_facebook
														%a.addthis_button_twitter
														%a.addthis_button_pinterest
														%a.addthis_button_stumbleupon
														%a.addthis_button_reddit
														%a.addthis_button_email
														%a.addthis_counter.addthis_bubble_style
													%script{:src => "http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e07edfe1206c99f", :type => "text/javascript"}
													-# %h6.center <<< link >>>
											%hr
									.row-fluid
										.span12
											= markdown @project.description
											%hr
									.row-fluid
										.span12
											= render 'comments/comments', commentable: @project
								.span4
									.row-fluid
										.span12
											%h2
												%span.pull-right= pluralize @project.energy, 'volt'
												%i.icon-bolt
											%hr
									.row-fluid
										.span12
											%h2
												%span.pull-right= pluralize @project.view_count, 'view'
												%i.icon-eye-open
											%hr
									.row-fluid
										.span12
											%h2
												%span.pull-right= pluralize @project.votes_for, 'star'
												%i.icon-star
											%hr
									.row-fluid
										.span12
											%h2
												%span.pull-right= @project.state
												State:
											%hr
									.row-fluid
										.span12
											= list_tags @project.tags
											%hr
									.row-fluid
										.span12
											%h6 Created by:
											.row-fluid
												.span4
													= link_to @project.user.profile, title: @project.user.username do 
														= image_tag @project.user.profile.avatar.image.medium, class: "circle"
												.span8
													%h3= link_to @project.user.username, @project.user.profile
													%h4= @project.user.name
													%h6
														= @project.user.projects.count
														= @project.user.projects.count == 1 ? 'project' : 'projects'
														&nbsp;
														%i.icon-briefcase
													%h6
														= @project.user.reputation
														reputation
														&nbsp;
														%i.icon-certificate
												
											%hr
									.row-fluid.members#project-members
										.span12
											%h2 
												%i.icon-group
												members
												%span.pull-right
													= render 'join_link', project: @project
											= render 'join_requests', project: @project  
											.row-fluid.list
												- @project.members.each do |user|
													.span2
														= link_to user.profile, title: user.username do 
															= image_tag user.profile.avatar.image.small, class: "circle", alt: user.username
											%hr 
									.row-fluid.participants
										.span12
											%h2
												%i.icon-comment
												participants
											.row-fluid.list
												- @project.participants.each do |user|
													.span2
														= link_to user.profile, title: user.username do 
															= image_tag user.profile.avatar.image.small, class: "circle", alt: user.username
											%hr 
									.row-fluid.followers
										.span12
											%h2 
												%i.icon-star
												followers
											.row-fluid.list
												- @project.followers.each do |user|
													.span2
														= link_to user.profile, title: user.username do 
															= image_tag user.profile.avatar.image.small, class: "circle", alt: user.username

											%hr

app/views/projects/update.js.erb
$('#project_<%= @project.id %> .project-vote [rel*=tooltip]').tooltip('hide');
$('#project_<%= @project.id %> .project-vote').replaceWith('<%= escape_javascript render("vote") %>');
$('#project_<%= @project.id %> .project-vote [rel*=tooltip]').tooltip();