config/routes.rb
Ananta::Application.routes.draw do

	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config

	post 'versions/:id/revert' => 'versions#revert', :as => 'revert_version'
	
	resources :sessions, :only => [:index]

	resources :comments, :only => [:index, :show, :create, :edit, :update, :destroy]
	resources :locations, :only => [:create, :update]

	resources :questions, :only => [:index, :show, :create, :update] do
		collection do
			get 'page/:page', :action => :index
			get 'random_unanswered'
		end
		resources :answers, :only => [:index, :show, :create, :update] do
			resources :comments, :only => [:create]
		end
	end

	resources :project_memberships, :only => [] do
		member do
			post 'accept'
			post 'reject'
		end
	end

	resources :projects, :only => [:index, :show] do
		collection do
			get 'page/:page', :action => :index
			get 'random'
		end
		resources :comments, :only => [:index]
	end

	resources :images, :only => [:create, :update, :destroy]

	match '/render_nav' => 'users#render_nav' # ujs render user_nav. generally called after ajax login
	resources :users, :only => [:index] do
		collection do
			get 'random'
		end
	end
	devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', :registrations => 'users/registrations', :sessions => 'users/sessions' }
	devise_scope :user do
		get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
		get '/login' => 'devise/sessions#new'
		get '/logout' => 'devise/sessions#destroy'
		get '/register' => 'devise/registrations#new'
	end

	match '/me' => 'pages#me' 
	match '/tb' => 'pages#tb' if Rails.env == 'development'
	match '/about' => 'pages#about'
	match '/robots.txt' => 'pages#robots'

	root :to => 'pages#home'

	resources :profiles, :path => '' do
		member do
			get :edit_location
		end
	end
	resources :users, :path => '', :only => [] do
		resources :projects, :path => '', :except => [:index] do
			member do
				post "join"
				post "leave"
			end
		end
	end

	# See how all your routes lay out with "rake routes"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# TODO: LAUNCH - remove this
	http_basic_authenticate_with :name => "infinite", :password => "panda" if %w(production sandbox).include?(Rails.env)
	
	protect_from_forgery

	analytical use_session_store: true, modules: [:console]                   	if %w(development sandbox test).include?(Rails.env)
	analytical use_session_store: true, modules: [:console, :mixpanel]        	if Rails.env == 'staging'
	analytical use_session_store: true, modules: [:mixpanel, :google, :clicky]	if Rails.env == 'production'

	before_filter :miniprofiler
	before_filter :set_markdown
	after_filter  :set_questionable, :if =>  lambda { request.format == 'html' }

	# Default cancan redirect url
	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_url, :alert => exception.message
	end

	# Initialize cancan
	def current_ability
		@current_ability ||= Ability.new(current_user, params)
	end

	# Devise after sign in hack     # TODO: make less hacky, maybe update the /users route?
	# def after_sign_in_path_for(resource)
	#	request.referer =~ /\/users/ ? root_url : super
	# end

	# Helper method for picking allowed keys from a hash of params
	# http://www.quora.com/Backbone-js-1/How-well-does-backbone-js-work-with-rails
	def pick(hash, *keys)
		filtered = {}
		hash.each do |key, value| 
			filtered[key.to_sym] = value if keys.include?(key.to_sym) 
		end
		filtered
	end

	# Helper to insert the Current User ID (cuid) into hash fields that need it
	# Adds nil if no current_user
	def add_cuid(hash, *keys)
		keys.each do |key|
			hash[key][:cuid] = (current_user.id rescue nil) if hash[key]
		end
		hash
	end

	def set_markdown
		unless $markdown
			rndr = Redcarpet::Render::HTML.new(filter_html: true, hard_wrap: true)
			$markdown = Redcarpet::Markdown.new(rndr, autolink: true, space_after_headers: false, strikethrough: true, superscript: true)
		end
	end

	# Store some params about the user's current page for use with marq questions
	def set_questionable
		session[:questionable_sid] = params[:id]
		session[:questionable_controller] = params[:controller]
		session[:questionable_url] = request.url
		session[:questionable_action] = params[:action]
	end

	# Override default behavior for testing on local machine 
	def remote_ip
		if request.remote_ip == '127.0.0.1'
			# Random remote address for testing on develop
			"#{rand(255)}.#{rand(255)}.#{rand(255)}.#{rand(255)}"
		else
			request.remote_ip
		end
	end

	def populate_tags model, *tags
		@tags = {}
		@selected_tags = {}
		tags.each do |tag|
			@tags[tag.to_s] = model.class.tag_counts_on(tag.to_sym).where("name like ?", "%#{params[:q]}%").map{|t| {:id => t.name, :name => t.name}}
			@selected_tags[tag.to_s] = model.send(tag.to_sym).map{|t| {:id => t.name, :name => t.name}}
		end
	end


private
	def miniprofiler
		Rack::MiniProfiler.authorize_request if current_user and current_user.admin?
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include Twitter::Extractor

	def tb_alert_name name
		tb_names = {'notice' => 'success'}
		tb_names[name.to_s] || name.to_s
	end

	def hovercard model
		render "#{model.class.to_s.downcase.pluralize}/hovercard", model: model
	end

	def list_tags tags
		render "tags/tags", tags: tags
	end

	def markdown(text)
		text ||= '' # markdown barfs on nil
		raw $markdown.render(text)
	end

	def tagged_markdown(text)
		text ||= ''

		usernames = extract_mentioned_screen_names(text).uniq
		tags = extract_hashtags(text).uniq

		usernames.each_with_index { |u, i| text = text.gsub(/@#{u}/, "ausrname#{i}") }
		tags.each_with_index { |t, i| text = text.gsub(/##{t}/, "ahshtag#{i}") }

		text = markdown text

		usernames.each_with_index { |u, i| text = text.gsub(/ausrname#{i}/, "<a href='#{root_url}#{u}'>@#{u}</a>") }
		tags.each_with_index { |t, i| text = text.gsub(/ahshtag#{i}/, "<a href='#{root_url}tags/#{t}'>##{t}</a>") }

		raw text
	end

	def toggle_sort attribute, display_name, path, model_name
		if request.path != path
			session["#{model_name.downcase}_sort_attribute"] = nil
			session["#{model_name.downcase}_sort_direction"] = nil
		end

		current_sort_attribute = session["#{model_name.downcase}_sort_attribute"]
		current_sort_direction = session["#{model_name.downcase}_sort_direction"]

		if attribute != current_sort_attribute
			new_sort_direction = 'desc'
			arrow = " <i class='icon-sort'></i>"
		elsif current_sort_direction == 'asc'
			new_sort_direction = 'desc'
			arrow = " <i class='icon-sort-up'></i>"
		elsif current_sort_direction == 'desc'
			new_sort_direction = 'asc'
			arrow = " <i class='icon-sort-down'></i>"
		end

		query = "?sort=#{attribute}&direction=#{new_sort_direction}"

		raw "#{link_to display_name, path + query, remote: true}#{arrow}" 
	end
end

app/views/application/_facebook.html.haml
#fb-root
:coffeescript
	window.fbAsyncInit = ->
		FB.init
			appId: "#{Facebook::APP_ID}"
			status: true
			cookie: true
			oauth: true
			frictionlessRequests: true
			xfbml: true

	((d) ->
		js = undefined
		id = "facebook-jssdk"
		return  if d.getElementById(id)
		js = d.createElement("script")
		js.id = id
		js.async = true
		js.src = "//connect.facebook.net/en_US/all.js"
		d.getElementsByTagName("head")[0].appendChild js
	) document

	window.fbLogin = (callback) ->
		login = (response) ->
			if callback
				callback response
			else
				$("a.btn-facebook").append "<img src=\"assets/ajax-loader-black-dots.gif\" class=\"loader\"/>"
				$.ajax
					url: "#{user_omniauth_callback_path(:facebook)}"
					success: (data) ->
						$("a.btn-facebook .loader").remove()
						user = data
						if user["id"]?
							console.log 'logged in'
							window.location.href = '/'
						else
							if window.loginModal
								callback = window.loginModal.callback
								window.loginModal.close()
							window.loginModal = new Ananta.Views.Users.LoginRegisterModal(
								callback: callback
								user: user
							)
							window.loginModal.render()
							
		FB.login ((response) ->
			if response.authResponse then login response 
		),
			scope: "#{Facebook::SCOPE}"

app/views/application/_flashes.html.haml
-# Options
-# (default) = yellow, error = red, notice (and) success = green, info = blue
-flash.each do |name, msg|
  -if msg.kind_of?(Array)
    -msg.each do |msg|
      %div{ title: name.to_s.humanize, class: "alert alert-#{tb_alert_name name}" }
        %span.close{ 'data-dismiss' => 'alert' } &times;
        = raw msg
  -else
    %div{ title: name.to_s.humanize, class: "alert alert-#{tb_alert_name name}" }
      %span.close{ 'data-dismiss' => 'alert' } &times;
      = raw msg

app/views/application/_footer.html.haml
=content_for :javascripts do
	:coffeescript
		$(() ->
			buttons = $("#footer .addthis_toolbox").children()  
			pre = 99
			cur = 0
			hover = false
			time = 3000
			$(buttons).fadeTo(0, 0.4);
			$(buttons).hide()
			transitionButtons = () =>
				cur = if (pre+1) < buttons.length then (pre+1) else 0
				$(buttons[pre]).fadeOut(500)
				$(buttons[cur]).fadeIn(500)
				pre = cur
				recur = () =>
					if hover
						wait time, () => recur()
					else
						transitionButtons()
				wait time, () => recur()
			transitionButtons()
			#
			$("#footer .addthis_toolbox").live
				mouseenter: =>
					hover = true
					$(buttons[cur]).fadeTo(300, 1.0);
				mouseleave: =>
					hover = false
					$(buttons[cur]).fadeTo(300, 0.4);
			.tooltip
				title: 'share this page'
				placement: 'top'
				delay: 
					show: 800
		)

.container
	.center
		ananta IO
		= image_tag "/assets/copyleft.png", style: "height: 10px"
		#{ Date.today.year }
		&middot;
		= link_to 'github', "https://github.com/ananta-io/ananta", target: "_blank"
		&middot;
		= link_to 'about', '/about'
		&middot;
		.addthis_toolbox.addthis_default_style
			%a.addthis_button_facebook_like{"fb:like:layout" => "button_count"}
			%a.addthis_button_tweet
			%a.addthis_button_google_plusone{"g:plusone:size" => "medium"}
			%a.addthis_button_pinterest_pinit{"p:pinit:size" => "medium"}
		:javascript
			var addthis_config = {"data_track_addressbar":true};
		%script{:src => "http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4e07edfe1206c99f", :type => "text/javascript"}
	
		- if Rails.env == 'staging'
			<a href="https://mixpanel.com/f/partner"><img src="https://mixpanel.com/site_media/images/partner/badge_light.png" alt="Mobile and Web Analytics" /></a>

app/views/application/_head.html.haml
/
	∙                                       --.-- .--.         
	∙                            _|_          |  :    :        
	∙         .-.  .--. .-.  .--. |  .-.      |  |    |        ○
	∙        (   ) |  |(   ) |  | | (   )     |  :    ;        
	∙         `-'`-'  `-`-'`-'  `-`-'`-'`-  --'-- `--'         

= raw analytical.head_prepend_javascript

%meta{ charset: "utf-8" }

-# Use the .htaccess and remove these lines to avoid edge case issues.
%meta{ "http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1" }

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }

%title
	- title = yield :title
	- if title.blank?
		= raw("#{controller.controller_name.titleize} | #{controller.action_name.titleize} \&middot; Ananta IO")
	- elsif title.include? "Ananta IO"
		= raw(title)
	- else
		= raw("#{title} \&middot; Ananta IO")
  
%meta{ name: "description", content: "" }
%meta{ name: "author", content: "" }

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

= render "stylesheets"

-# More ideas for your <head> here: h5bp.com/d/head-Tips

- unless Rails.env.test?
	-# All JavaScript at the bottom, except this Modernizr build incl. Respond.js
	-# Respond is a polyfill for min/max-width media queries. Modernizr enables HTML5 elements & feature detects;
	-# for optimal performance, create your own custom Modernizr build: www.modernizr.com/download/
	= javascript_include_tag "polyfills"
	= javascript_include_tag "css_browser_selector"
	= javascript_include_tag "http://js.pusherapp.com/1.9/pusher.min.js"
	-# = javascript_include_tag "http://use.typekit.com/yng4qye.js"
	-# :javascript
	-#   try{Typekit.load();}catch(e){}

= csrf_meta_tag

- analytical.identify( current_user.id, { name: current_user.username } ) if current_user
- analytical.set( { user_id: current_user.id, user_created_at: current_user.created_at, user_sign_in_count: current_user.sign_in_count, user_last_sign_in_at: current_user.last_sign_in_at, username: current_user.username } ) if current_user
= raw analytical.head_append_javascript

app/views/application/_header.html.haml
=content_for :javascripts do
	:javascript
		$(function() {
			// Add marq to view
			Ananta.App.marqRouter = new Ananta.Routers.MarqRouter({
				q_controller: "#{params[:controller]}",
				q_action: "#{params[:action]}",
				q_sid: "#{params[:id]}"
			});
			// Backbone.history.start();
		});
		// Open and close marq
		$('#marq_toggle a').click(function(e) {
			$('#marq_toggle a').toggleClass('active');
			$('#marq').slideToggle('fast');
			if($('#marq_toggle a.active').length > 0){
				Analytical.event('Manually Open Marq', { location: window.location.href } );
			}else{
				Analytical.event('Manually Close Marq', { location: window.location.href } );
			};
			e.preventDefault();
			e.stopPropagation();
		});
		// Auto open marq
		// $('#marq_toggle a').toggleClass('active');
		// $('#marq').slideToggle('fast');

-# Marq slide down container
-# Starts as display:none
#marq
	.center
		%br
		= image_tag "ajax-loader-small.gif"
		%br
		%br

-# Top Nav
.navbar
	.container-fluid
		.user-nav
			= render 'user_nav'  
		-# Center
		%ul.nav.center
			%li#marq_toggle
				= link_to "?", "#"

app/views/application/_javascripts.html.haml
-# Add the application js
= javascript_include_tag "application"
			
-#  Append your own using content_for :javascripts
= yield :javascripts

- unless Rails.env.test?
	-# Google Maps
	%script{ src: "http://maps.googleapis.com/maps/api/js?key=#{Rails.env == 'development' ? 'AIzaSyCDoOtoUcsKP8lyeMZtpy5lCs0GcEPP6C8' : ENV['GOOGLE_API_KEY']}&sensor=false"}
	
	-# Add the google js api for goodies like charts
	%script{ src: "https://www.google.com/jsapi" }
	:javascript
		google.load('visualization', '1.0', {'packages':['corechart']});

	-# Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
	-# chromium.org/developers/how-tos/chrome-frame-getting-started
	/[if lt IE 9 ]
		%script{ defer: true, src: "//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js" }
		%script{ defer: true } window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})

	-# Intercom.io
	- if current_user
		:plain
			<script id="IntercomSettingsScriptTag">
				var intercomSettings = {
					app_id: '#{Rails.env == "development" ? "y5m7xjrv" : ENV["INTERCOM_APP_ID"]}',
					email: '#{current_user.email}',
					created_at: #{current_user.created_at.to_time.to_i},
					name: '#{current_user.name}',
					user_id: '#{current_user.id}',
					custom_data: {
						'username': '#{current_user.username}'
					}
				};
			</script>
			<script>
				(function() {
					function async_load() {
						var s = document.createElement('script');
						s.type = 'text/javascript'; s.async = true;
						s.src = 'https://api.intercom.io/api/js/library.js';
						var x = document.getElementsByTagName('script')[0];
						x.parentNode.insertBefore(s, x);
					}
					if (window.attachEvent) {
						window.attachEvent('onload', async_load);
					} else {
						window.addEventListener('load', async_load, false);
					}
				})();
			</script>

app/views/application/_notifications.html.haml
= content_for :javascripts do
	:javascript
		Tinycon.setBubble('#{current_user.notifications.unviewed.count}');

%li.nav-header
	-if count = current_user.notifications.unviewed.count and count > 0
		%span.pull-right.color-no= count
	- else
		%span.pull-right= count
	%i.icon-inbox
	notifications
- current_user.notifications.unviewed.each do |notification|
	- url = notification.url ||= "#"
	%li
		= link_to url do
			- case notification.notifiable_type
			- when "Comment"
				%i.icon-comment-alt.color-no
			- when "ProjectMembership"
				%i.icon-user.color-no
			- when "Project"
				%i.icon-wrench.color-no
			- else
				%i.icon-bullhorn.color-no
			= raw notification.message

app/views/application/_stylesheets.html.haml
-# CSS: implied media="all"
= stylesheet_link_tag 'application', :media => 'all'

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/application/_user_nav.html.haml
-# Left
- if !current_user and request.path == '/'
	%a.brand{:href => "/"}
		ananta IO
- else
	%a.brand{:href => "/"} 
		ananta IO
		%i.icon-home
-# Right
%ul.nav.pull-right
	-if current_user
		-#
			%li
				%a.search
					%i.icon-search
					%i.icon-chevron-left
		%li
			= link_to random_unanswered_questions_path do
				%i.icon-random

		%li.dropdown.projects
			%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
				%i.icon-briefcase
				%i.icon-chevron-down
			%ul.dropdown-menu
				%li.nav-header
					= link_to new_user_project_path(current_user), :class => 'pull-right' do
						%i.icon-plus
					%i.icon-list-alt
					My projects
				- current_user.projects.each do |project|
					%li
						= link_to [current_user, project] do
							%i.icon-wrench
							= project.name
				%li.divider
				%li.nav-header
					%i.icon-list-alt
					Joined projects
				%li.divider
				%li.nav-header
					= link_to random_projects_path, :class => 'pull-right' do
						%i.icon-random
					%i.icon-wrench
					All projects
				%li
					= link_to projects_path do
						%i.icon-th
						Explore projects
						
		%li.dropdown.user
			%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
				%i.icon-user
				- if count = current_user.notifications.unviewed.count and count > 0
					%span.count
						= count
				%i.icon-chevron-down
			%ul.dropdown-menu
				%li.nav-header
					%span.display-inline-block
						= link_to current_user.profile do
							= image_tag current_user.profile.avatar.image.small.url, width: 24, height: 24, class: 'circle'
					= current_user.username
				%li
					= link_to current_user.profile do
						%i.icon-user
						my profile
				%li
					= link_to edit_profile_path(current_user.profile) do
						%i.icon-cogs
						settings
				%li
					= link_to "/logout" do
						%i.icon-signout
						logout
				%li.divider
				= render "application/notifications"
				%li.divider
				%li.nav-header
					= link_to random_users_path, :class => 'pull-right' do
						%i.icon-random
					%i.icon-group
					All people
				%li
					= link_to users_path do
						%i.icon-th
						Explore people
				
	-else
		%li
			= link_to random_unanswered_questions_path do
				%i.icon-random
		%li
			= link_to projects_path do
				%i.icon-th
		%li
			%a.login
				%i.icon-signin